apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  creationTimestamp: null
  name: todo-api-deploy
spec:
  maxReplicas: 3
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: todo-api-deploy
  targetCPUUtilizationPercentage: 90
status:
  currentReplicas: 0
  desiredReplicas: 0
