apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"kind":"Deployment","apiVersion":"apps/v1","metadata":{"name":"todo-api-deploy","creationTimestamp":null,"labels":{"app":"todo-api-deploy"}},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"todo-api-deploy"}},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"todo-api-deploy"}},"spec":{"containers":[{"name":"todo-api","image":"gaelroustan/todo-api:2.0","ports":[{"containerPort":3002}],"resources":{}}]}},"strategy":{}},"status":{}}
  creationTimestamp: null
  labels:
    app: todo-api-deploy
  name: todo-api-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-api-deploy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: todo-api-deploy
    spec:
      containers:
      - image: gaelroustan/todo-api:2.0
        name: todo-api
        ports:
        - containerPort: 3002
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 250m
status: {}
