apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: todo-api-service
  name: todo-api-service
spec:
  ports:
  - name: 3002-30002
    port: 3002
    protocol: TCP
    targetPort: 30002
  selector:
    run: todo-api-pod
  type: NodePort
status:
  loadBalancer: {}
