apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: todo-api-deploy
  name: todo-api-svc-lb
spec:
  ports:
  - port: 3002
    protocol: TCP
    targetPort: 3002
  selector:
    app: todo-api-deploy
  type: LoadBalancer
status:
  loadBalancer: {}
